/// spec-35 phase O: rotierende fiktive Markt-News auf der Springboard.
/// Reine Strings — keine Mechanik. Mood-Setting + Lern-Anreize.
abstract final class NewsPool {
  static const items = <String>[
    '📈 WeltTec-Aktie auf neuem Hoch',
    '💼 Lohnerhöhung in vielen Firmen: +5 %',
    '🌍 EZB lässt den Zins gleich',
    '🥇 Gold-Preis fast so hoch wie noch nie',
    '₿ Bitcoin schwankt heute wieder stark',
    '🏠 Wohnen wird wieder teurer — Mieten steigen',
    '📊 DAXION 40 schließt mit +0,4 %',
    '🔻 NordOel-Aktie fällt nach Geschäftszahlen',
    '⚡ Energie-Firmen unter Druck',
    '📰 Preise im Schnitt 2,3 % höher als letztes Jahr',
    '🌱 Banken zahlen weniger Zins auf Sparkonten',
    '💰 ETF-Sparer bekommen viele Dividenden',
    '🎓 Studie: Wer jung anfängt zu sparen, hat doppelt so viel mit 60',
    '🛡 Behörde warnt vor Krypto-Betrugs-Coins',
    '💎 Platin teurer als Palladium',
    '🏦 Online-Broker: Sparplan jetzt komplett gebührenfrei',
    '🌧 Regen-Sommer drückt Konsum — weniger Eis verkauft',
    '☀ Sommer treibt Bauwirtschaft: Häuser +3 %',
    '🚨 Inflation flacht weiter ab — gute Nachricht',
    '🤖 KI-Boom treibt Tech-ETFs nach oben',
    '🎯 Tipp: Erst Notgroschen, DANN investieren',
    '📉 Aktien aus Schwellenländern fallen weiter',
    '💡 Wusstest du? Erste 1.000 € Gewinn pro Jahr = steuerfrei',
    '🏘 Neue Regel: Wohnungsbau wird einfacher',
    '⏳ Lange dranbleiben schlägt Markt-Timing',
    '🎨 Junge Leute kaufen immer mehr ETFs',
    '⚖ Versicherer: Berufsunfähigkeit oft nicht abgesichert',
    '📊 Schnitt-Vermögen DE: 106.000 € pro Haushalt',
    '🌳 Grüne Fonds wachsen weiter',
    '🛒 Lebensmittel-Preise +1,8 % gegen letztes Jahr',
    '🔄 Tipp: Streuung schützt vor großen Verlusten',
    '🐢 Geduld zahlt sich aus — alte Anleger-Weisheit',
    '🎉 Gute Quartalszahlen bei vielen Welt-Konzernen',
  ];
}
